"""Test module to collect compile time metrics. This just finds and summarizes
the *.json files generated by the build."""
from litsupport.modules import timeit

import json
import os
from enum import Enum

class TimeID(Enum):
    TOTAL = "Total ExecuteCompiler"
    OPT = "Total Optimizer"
    GVN = "Total GVNPass"
    NewGVN = "Total NewGVNPass"
TIMEID_VALUES = {t.value for t in TimeID}

def _getCompileTime(context):
    # We compile multiple benchmarks in the same directory in SingleSource
    # mode. Only look at compiletime files starting with the name of our test.
    prefix = ""
    if context.config.single_source:
        prefix = "%s." % os.path.basename(context.executable)

    compile_times = {time_id.value: 0.0 for time_id in TimeID}
    dir = os.path.dirname(context.test.getFilePath())
    for path, subdirs, files in os.walk(dir):
        for file in files:
            if file.endswith(".c.json") and file.startswith(prefix):
                fullpath = os.path.join(path, file)
                with open(fullpath, "r") as timefile:
                    trace_data = json.load(timefile)
                    for event in trace_data.get("traceEvents", []):
                        duration = float(event.get("dur", 0)/10e6)
                        if event.get("name") in TIMEID_VALUES:
                            compile_times[event.get("name")] += duration
    return {
        "compile_time_total": compile_times[TimeID.TOTAL.value],
        "compile_time_optimizer": compile_times[TimeID.OPT.value],
        "compile_time_gvn": compile_times[TimeID.GVN.value] + \
                            compile_times[TimeID.NewGVN.value],
    }


def mutatePlan(context, plan):
    plan.metric_collectors.append(_getCompileTime)
